<?php
/**
 * Created by PhpStorm.
 * User: Lenovo
 * Date: 2016/12/9
 * Time: 9:10
 */

namespace liumapp\library\assets;


use yii\web\AssetBundle;

class ZTreeAsset extends AssetBundle
{
    public $sourcePath = '@bower/ztree_v3/';

    public $theme = 'zTree';

    public $js = [
        'js/jquery.ztree.all.min.js'
    ];

    public $depends = [
        'liumapp\library\assets\UIAsset'
    ];

    public $publishOptions = [
        'except'=>['/api/','/demo/']
    ];
    public function init()
    {
        $themes = [
            'zTree'=>'css/zTreeStyle/zTreeStyle.css',
            'metro'=>'css/metroStyle/metroStyle.css',
            'awesome'=>'css/awesomeStyle/awesome.css',
        ];
        $this->css = [
            $themes[$this->theme]
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}